/* eslint-disable camelcase */
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const itemSchema = new Schema({
    state: {type: String, required: true},
    new_listing: {type: String, required: true},
    title: {type: String, required: true},
    condition: {type: String, required: true},
    inventory: {type: Number, required: true},
    sku: {type: String, required: true},
    make: {type: String, required: true},
    model: {type: String, required: true},
    description: {type: String, required: true},
    year: {type: String, required: true},
    finish: {type: String, required: true},
    price: {type: String, required: true},
    product_type: {type: String, required: true},
    subcategory_1: {type: String, required: true},
    subcategory_2: {type: String, required: true},
    product_image_1: {type: String, required: true},
    product_image_2: {type: String, required: true},
    product_image_3: {type: String, required: true},
    product_image_4: {type: String, required: true},
    product_image_5: {type: String, required: true},
    product_image_6: {type: String, required: true},
    product_image_7: {type: String, required: true},
    product_image_8: {type: String, required: true},
    product_image_9: {type: String, required: true},
    product_image_10: {type: String, required: true},
    product_image_11: {type: String, required: true},
    product_image_12: {type: String, required: true},
    product_image_13: {type: String, required: true},
    product_image_14: {type: String, required: true},
    product_image_15: {type: String, required: true},
    product_image_16: {type: String, required: true},
    product_image_17: {type: String, required: true},
    product_image_18: {type: String, required: true},
    product_image_19: {type: String, required: true},
    product_image_20: {type: String, required: true},
    product_image_21: {type: String, required: true},
    product_image_22: {type: String, required: true},
    product_image_23: {type: String, required: true},
    product_image_24: {type: String, required: true},
    product_image_25: {type: String, required: true},
    video_url: {type: String, required: true},
    offers_enabled: {type: String, required: true},
    shipping_price: {type: String, required: true},
    combine_and_save_shipping_price: {type: String, required: true},
    local_pickup: {type: String, required: true},
    shipping_profile_name: {type: String, required: true},
    seller_cost: {type: String, required: true},
    tax_exempt: {type: String, required: true},
    upc: {type: String, required: true},
    upc_does_not_apply: {type: String, required: true},
    published_at: {type: String, required: true},
    url: {type: String, required: true},
    prop_65_warning: {type: String, required: true},
    id: {type: String, required: true},
    preorder_lead_time: {type: String, required: true},
    preorder_ship_date: {type: String, required: true},
    bump_rate: {type: String, required: true},
    bump_rate_recommendation: {type: String, required: true},
    sold_as_is: {type: String, required: true},
    country_of_origin: {type: String, required: true},
});

const Item = mongoose.model('Item', itemSchema);

module.exports = Item;
